### ISSUE TITLE
imagej-utils dependency

### ISSUE THREAD

**Issue by tischi** [mobie/bigdataviewer-ome-zarr#3]
[Here](https://github.com/mobie/bigdataviewer-ome-zarr/blob/cf1a7c0871e64afb63960f8b8a78002572999f25/src/main/java/de/embl/cba/bdv/ome/zarr/source/LabelConverter.java#L32), we depend on imagej-utils.

Not sure how to handle this....

**Comment by constantinpape** [comment]
For now, this repository will not treat label images differently, so we don't need any of this functionality here.
